# -*- coding: utf-8 -*-
"""Variables and Its Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXXwENQJ3X36xB-_cW8fqfYZ5siBYrFd

String
"""

Name="He is very Innocent"
print(Name)

A="Ali is my Brother"
B=" He is very innocent"
print(A+B)

a="Pakistan is very Beautiful Country"
b="Usman is very innocent"
c=b
print(c)

a="Web Development Basics"
print(a)

my_var="Introduction to Python Programming"
My_var=" Python is very easy language"
print(my_var+My_var)

A="Aliza"
B="Javed"
print(A+B)

a="Usman"
A="Saeed"
print(a)

Name="Hum Bahir Ja Rahe Hain"
name="Jis Ne Ana Hai Woh Aa Jai"
print(Name+name)

a="Ali is Waiting"
b=" at Resturant"
print(a+b)

"""**Integer**"""

a=12
b=26
print(a+b)

a=25376
b=1527
print(a-b)

a=354
b=23
print(a*b)

a=243
b=354
print(a/b)

a=2453
b=23
print(a%b)

a=1653
b=354
c=a
print(a+b)

a=12653
b=4253
c=35664
d=1233
print(a-b+c+d)

a=3546
b=4567
c=64563
d=7363
e=63539
f=36527
print(a+b+c+d-e+f)

a=635
b=63
c=65
d=234
print(a*b/c-d)

a=356
b=23
c=645
d=334
print(a%b+c*d)

"""**Float**"""

a=23.4
b=75.4
print(a+b)

a=46.675
b=78.987
c=53.999
print(a-b+c)

num1=34.45
num2=98.55
num3=99.9
print(num1+num2+num3)

student_1=657.44
student_2=348.32
print(student_1+student_2)

a=456.44
b=465.33
c=667.77
print(a*b*c)

s1=35.44
s2=78.85
print(s1%s2)

g=9.3746
h=8.6363
i=7.5353
print(g*h/i)

marks1=98.4
marks2=99.9
print(marks1+marks2)

a=44.44
b=83.44
c=76.98
print(a*b+c)

a=546.77
b=635.73
c=736.90
d=653.33
e=999.76
print(a+b-c*d/e)

"""**Boolean**"""

a=True
b=False
print(a or b)

a=True
b=False
print(a is b)

g=True
h=False
print(not b)

a=True
b=False
print(a is b)

j=False
i=True
print(i or j)

u=True
o=False
print(not o)

u=False
o=True
print(not o)

f=True
l=False
print(l is f)

m=True
n=False
print(n or m)